            - name: .NET Core CLI
  # You may pin to the exact commit or the version.
  # uses: baruchiro/github-actions@cfa460ee18f07031ba85ff00d2184fabf03f9f1f
  uses: baruchiro/github-actions@0.0.1
          
